[project]
name = "models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.1",
    "opencv-python>=4.11.0.86",
    "opencv-stubs>=0.1.1",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
]
